apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-frontend-deployment
  labels:
    app: pokedex-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokedex-frontend
  template:
    metadata:
      labels:
        app: pokedex-frontend
    spec:
      containers:
        - name: pokedex-frontend
          image: fedd911/pokedex-project-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pokedex-frontend-service
spec:
  selector:
    app: pokedex-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80